components/ord-service/Dockerfile, components/ord-service/Makefile, components/ord-service/run.sh, components/ord-service/scripts/build.sh, components/ord-service/scripts/install_dependencies.sh
- Improve build, test and release scripts in order to make developing and testing easier
- Introduce `--no-start` and `--skip-tests` flags to `run.sh` script
=> Improve build, test and release scripts

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/filter/ResponseFormatFilter.java, components/ord-service/src/main/resources/application.yml, components/ord-service/src/test/resources/application.yml
- Allow specifying the default response format via new `ResponseFormatFilter`
=> Introduce Default Response Format filter

components/ord-service/Dockerfile, components/ord-service/pom.xml, components/ord-service/run.sh
Improves build time of the Docker image, by first resolving dependencies and using layer caching.
=> Download olingo before copying source code

README.md
Update the Readme file with information about the newly introduced `tenant` header.
=> Update README.md with tenant header info

components/ord-service/pom.xml
- Bump dependencies due to their vulnerabilities.
=> Bump netty version

components/ord-service/pom.xml
=> Update dependencies 

components/ord-service/pom.xml
=> bump org.springframework.boot to 2.4.4

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/config/EclipseLinkJpaConfiguration.java
- Decrease max DB open connections to 2
=> Decrease ord-service max DB open connections

components/ord-service/pom.xml, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/config/EclipseLinkJpaConfiguration.java
=> Adopt jpa-processor 0.3.9

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/config/EclipseLinkJpaConfiguration.java, components/ord-service/src/main/resources/application.yml
- Manage used connections with CP settings. The details about **Hikari Connection Pool** settings can be seen [here](https://github.com/brettwooldridge/HikariCP).
=> Manage used connections with CP settings

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ExtensibleEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
=> Adapt rc3 changes

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
=> Ord rc4 adaptation

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
This PR introduces adaptations and fixes regarding the adaption of ORD v1.
=> Adapt ord v1

components/ord-service/pom.xml
- Update Spring boot version
- Update PostgreSQL driver version
- Update Eclipselink version
=> [CMP-710] Update dependencies

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
This PR introduces GUID ID field for Tombstones, Vendors and Products. In addition, some relations between resources were adapted due to changes in the underlying views.
- https://github.com/kyma-incubator/compass/pull/1912
=> Introduce internal ids

components/ord-service/Dockerfile, components/ord-service/pom.xml
=> Bump Java version 

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
See: https://github.com/kyma-incubator/compass/pull/1967
=> Enable formation filtering

components/ord-service/run.sh, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/health/ReadinessHealthIndicator.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SchemaRepository.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SchemaEntity.java, components/ord-service/src/main/resources/application.yml
- add readiness health indicator
=> add readiness indicator

components/ord-service/pom.xml
- Bumping spring-boot with latest patch version, which probably eliminates a netty vuln
- ...
- ...
=> Bump spring boot

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/filter/aggregator/JsonArrayElementsAggregator.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ExtensibleEntity.java
Fix extensible entity description length and various array items compact version.
=> Fix extensible description

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/health/ReadinessHealthIndicator.java
System.getenv is reported as a Low vulnerability.
=> Do not use System.getenv

components/ord-service/pom.xml
**update spring boot version to 2.5.6**
- Update the version of spring boot as it has a dependency to tomcat version
=> update spring boot version to 2.5.6

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
- Adapt all entities to use views
=> Adopt storage redesing

components/ord-service/pom.xml, components/ord-service/src/main/resources/application.yml
=> Update SB version

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleReference.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ConsumptionBundleReference.java
This PR introduces a new boolean field to the BundleReference entity which indicates whether or not the specific Bundle is default for the referenced entity (API/Event)
=> Introduce defaultBundle for APIs/Events

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
- Add documentation labels to Products, Vendors, Consumption Bundles, API definitions, Event definitions, System Instances and Packages
Related PR: https://github.com/kyma-incubator/compass/pull/2157
=> Add documentation labels

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
Integration with ORD Global Registry that provides global product and vendors centrally.
=> ORD Global Registry for global products / vendors

components/ord-service/pom.xml
Update Spring Boot version, as the only supported vulnerability-free `postgresql` version is supported fron the 2.6 versions.
According to the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#upgrading-from-spring-boot-25), there are no changes required for our use cases.
- Update Spring Boot to v2.6.3
=> Update Spring Boot to v2.6.3

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
Add new support_info filed
https://github.com/kyma-incubator/compass/pull/2223
=> Add SupportInfo on ORD Packages

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
This PR increases the max accepted length of the `short_description` field in all related entities.
=> Increase short_description field length

components/ord-service/run.sh
- Add auto terminate option to local run script
=> Add auto terminate option

components/ord-service/Dockerfile, components/ord-service/pom.xml
- bump base image
- bump spring boot version
=> bump dependency version

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/Extensible.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/RootEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SchemaEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/APIDefinitionEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/APIExtensible.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/APIProduct.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/APIResourceLinkEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/APISuccessor.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/BundleReference.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/Changelog.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationId.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/Country.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CredentialExchangeStrategyEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabel.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EntryPoint.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EventDefinitionEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EventExtensible.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EventProduct.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EventSuccessor.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/Industry.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LineOfBusiness.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/PackageLinkEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/PackageProduct.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/Partner.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/Tag.java, docs/array-querying.md
- Helper Entity is created for each Embeddable type in order to enable OData querying.
- Documentation for querying on arrays
Fix for: https://github.com/SAP/olingo-jpa-processor-v4/issues/109
=> Enable rich querying by Complex Type

components/ord-service/pom.xml, components/ord-service/scripts/install_dependencies.sh
Downport of https://github.com/SAP/olingo-jpa-processor-v4/pull/157 and https://github.com/SAP/olingo-jpa-processor-v4/pull/158 in a fork until we adopt latest version and contribution is merged.
=> Tenancy on Embeddable entities & Joins Optimisation

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/SpecificationsController.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SpecRepository.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
Change tenant ids to be uuid from string.
=> Change tenant IDs from string to uuid

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/client/DestinationFetcherClient.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/config/DestinationFetcherConfig.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/filter/DestinationForceReloadFilter.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/filter/DestinationSensitiveDataFilter.java, components/ord-service/src/main/resources/application.yml, components/ord-service/src/test/java/com/sap/cloud/cmp/ord/service/destinations/DestinationFetcherClientTest.java, components/ord-service/src/test/java/com/sap/cloud/cmp/ord/service/destinations/FetchingDestinationsTest.java, components/ord-service/src/test/resources/application.yml
- Forward x-request-id header when calling the destination fetcher
=> Forward x-request-id header to destination fetcher

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
- Adopt ORD 1.1.4
Related PR: https://github.com/kyma-incubator/compass/pull/2914
=> Adopt ORD 1.1.4

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
- exposed optional version and local_tenant_id from consumption bundles
- exposed optional local_tenant_id from apis
- exposed optional local_tenant_id from events
- exposed optional local_tenant_id from system instances
**Related PR(s)**
- https://github.com/kyma-incubator/compass/pull/3001
=> Adapt latest ORD specification - from 1.2.0 to 1.2.2

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
This PR improves the formation filtering in the consumer-provider flow. Currently, if we are in it but there are no formations the runtimeContext (subscriber) is part of, we don't set any formation claims which then results in misleading error `Missing or invalid tenantID` instead of returning empty array of the given Entity.
The improvement in this case is to set a designated claim (different from the default one & the formation ID) which will be used only in the consumer-provider flow when there are no formations, so that no records will match from the views and we will return an empty array of the Entity.
=> Improve empty formations case in consumer-provider flow

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
- ...
- ...
- ...
https://github.com/kyma-incubator/compass/pull/3306
=> Adopt latest ORD specification - v1.3.0 + v1.3.2 + v1.3.3

CODEOWNERS, OWNERS, OWNERS_ALIASES
=> Add OWNERS files

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/SpecificationsController.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/filter/aggregator/JsonArrayElementsAggregator.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SpecRepository.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/CapabilityDefinition.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/CapabilityEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdCapability.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelCapability.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityCapability.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityCapability.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagCapability.java
In v1.4.0 of ORD Specification Capability resource with Capability Specification definition is added.
Also there is a new field `lastUpdate` in API, Event and Capability.
- Added CapabilityEntity and CapabilityDefinition
- Added `lastUpdate` field to APIEntity, EventEntity and CapabilityEntity
https://github.com/kyma-incubator/compass/pull/3355
=> Adopt latest ORD specification - v1.4.0, v1.4.1 and v1.4.2

components/ord-service/pom.xml, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/ChangelogEntityType.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdEntityType.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelEntityType.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EntityTypeProduct.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EntityTypeSuccessor.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityEntityType.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityType.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagEntityType.java
- v1.6.0
- Update dependencies
=> Adopt ORD specification 

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectAPIResource.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectEventResource.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectEventResourceSubset.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/IntegrationDependencyEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ResourceLink.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/AspectEventResourceSubset.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdIntegrationDependency.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelIntegrationDependency.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EventResourceLinkEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/IntegrationDependencySuccessor.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityIntegrationDependency.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityIntegrationDependency.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/RelatedIntegrationDependencies.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagIntegrationDependency.java
This PR adds the `IntegrationDependecy` entity along with its subentities. The `Aspect` entity and its `Even/APIResource` are modelled as a separate standalone entities instead of being embeddable because due to the big depth of nested subresources the relations between the entities could not be represented correctly/efficiently.
- ...
- ...
- ...
- https://github.com/kyma-incubator/compass/pull/3429#partial-pull-merging
=> Add IntegrationDependency and Aspect entities

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/CapabilityEntity.java
This PR adds missing tenant_id and formation_id fields to the Capabilities entity. When they were missing, the performance was extremely bad because there was no filtering in the SQL queries for that entity.
- ...
- ...
- ...
=> Add tenant and formation id to capability

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
- expose API entity under System Instance
- expose Event entity under System Instance
- kyma-incubator/compass#3538
=> Expose APIs and Events directly under system instances

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SelfRegisteredRepository.java
- Filter formations by discovery consumers allowlist of the formation template
- https://github.com/kyma-incubator/compass/pull/3566
=> Filter formations by discovery consumers allowlist of the formation template

components/ord-service/Dockerfile
=> Update base image

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
- ...
- ...
- ...
https://github.com/kyma-incubator/compass/pull/3576
=> Add lastUpdate property to Consumption Bundle Entity

components/ord-service/pom.xml
- SpringBoot Update
- https://github.com/kyma-incubator/compass/pull/3658
=> SpringBoot Update

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/FormationDetails.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java
This PR adds new `FormationDetails` field to the `SystemInstance`. It is modelled as `@Embedded` and is protected/filtered by its `targetId` field which should match the id of the caller (subscribed Application or RtCtx)
- add new `FormationDetails` class
- add new `caller_id` claim which holds the internal ID of the subscribed Application or RtCtx
- rename default claim to have a generic name since it is used on two semantically different places now
=> Expose information about the formation type, formation and formation assignment

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SelfRegisteredRepository.java, components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java, components/ord-service/src/test/java/com/sap/cloud/cmp/ord/service/destinations/FetchingDestinationsTest.java
Add additional application tenant check by label key `global_subaccount_id`.
- https://github.com/kyma-incubator/ord-service/pull/123
=> Extend application tenant check

components/ord-service/Dockerfile, components/ord-service/run.sh
=> Switch builder image to alpine based image
