kyma-incubator/ord-service

components/ord-service/Dockerfile

OpenJDK official images for [JRE 8](https://hub.docker.com/_/openjdk?tab=tags&page=1&ordering=last_updated&name=8-jre-alpine) are more than 2 years old. 
AdoptOpenJDK images are more frequently updated and their [alpine-jre](https://hub.docker.com/r/adoptopenjdk/openjdk8/tags?page=1&ordering=last_updated&name=alpine-jre) image is 2 days old. 
- Adopt fresh image from AdoptOpenJDK project based on Alpine and with JRE 8

Switch to adoptopenjdk JRE image

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ConsumptionBundleReference.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java

Currently, the relation between Bundles and Apis/Events is One-to-Many (a single Bundle can have many Apis/Events but a single Api/Event can be part of only one Bundle).
This PR introduces Many-to-Many relation between Bundles and Apis/Events (a single Bundle can have many Apis/Events and a single Api/Event can be part of many Bundles) due to ORD requirements. 
In addition, there are changes and adaptations to fields corresponding to ORD RC2.
-

Adapting ORD RC2 

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/SpecificationsController.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java

Currently, the ORD service returns the specs in plain text. This causes issues with the accept headers and would be better if the proper mime-type is returned

Return proper media type for specifications

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/converter/UrlConverter.java
components/ord-service/src/main/resources/application.yml
components/ord-service/src/test/java/com/sap/cloud/cmp/ord/service/storage/model/converter/UrlConverterTest.java
components/ord-service/src/test/resources/application.yml

With https://github.com/kyma-incubator/compass/pull/1981 ORD Service will be hosted on two different gateways (base urls), therefore we need to get the baseURL dynamically from the request.

Use baseURL from request context for spec URL instead of env

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java

We can expose additional metadata in the System Instance entity on top of ORD.
Newly exposed fields:
- Product Type
- System Number

Expose additional System Instance metadata

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/health/ReadinessHealthIndicator.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIProduct.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleReference.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventProduct.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageProduct.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java

This PR enables the ORD Service to support some odata filtering queries (`any`, `all` operators).
- some new entities are added expressing the ManyToMany relation between the current ones.
- PK of `ProductEntity` is changed from `ordId` to `id` field
- based on the changed views, the join columns in the `@ManyToMany` relation between the entities are reduced/optimized
- a default value is set to the schema migration version regarding the readiness probe (without it running the ORD Service in debug mode fails)

Allow extensive ord querying

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/Controller.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/SpecificationsController.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SpecRepository.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java

This PR makes changes in the ORD service which ensures that providers can access the api/event specifications of their consumers.
**Changes proposed in this pull request:**
- Extend extractInternalTenantIdFromIDToken to extract all tenants
- Extend ODataController to set all tenants as JPAClaimPairs
- Add provider_tenant property to the API models to reflect the structure of the new views introduced [here](https://github.com/kyma-incubator/compass/pull/2025). These new fields are @EdmProtectedBy the new provider_tenant coming in the ID token

Allow providers to read consumers' specs

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/health/ReadinessHealthIndicator.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SchemaEntity.java

Components should not be considered ready if the desired DB migration has failed.

Respect dirty flag on schema version in readiness probe

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/health/ReadinessHealthIndicator.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SchemaEntity.java

Components should not be considered ready if the desired DB migration has failed.

[HOTFIX] Respect dirty flag on schema version in readiness probe

---

components/ord-service/Dockerfile

There are several reported vulnerabilities, and @dzahariev opened an [issue](https://giters.com/AdoptOpenJDK/openjdk-docker/issues/615) on `adoptopenjdk` side, where they said that we should switch to `eclipse-temurin` 
- Replace `adoptopenjdk/openjdk11:alpine-jre` with corresponding and newer `eclipse-temurin:11.0.13_8-jre-alpine` image

Bump JRE image

---

components/ord-service/Dockerfile
components/ord-service/Makefile
components/ord-service/pom.xml

- bump builder image version from `3.8.4-eclipse-temurin-11` to `3.8.6-eclipse-temurin-11`
- bump eclipse-temurin image version from `11.0.15_10-jre-alpine` to `11.0.16_8-jre-alpine`
- bump spring boot starter version from `2.6.8` to `2.6.11`
- kyma-incubator/compass#2575
- kyma-incubator/compass-console#70

Bump docker image version

---

scripts/generic_make_go.mk

- remove `deploy-on-minikube` and `build-on-minikube` from Makefile
- add `deploy-on-k3d` and `build-for-k3d` to Makefile

Adapt deploy-on-minikube for k3d

---

scripts/generic_make_go.mk

Remove pull-licenses as no longer required. See: https://github.com/kyma-incubator/compass/pull/2656
- remove license-puller requirements

remove license-puller requirements

---

components/ord-service/Dockerfile
components/ord-service/pom.xml

- bump builder base image from `maven:3.8.6-eclipse-temurin-11` to `maven:3.8.7-eclipse-temurin-11-focal`
- bump runtime base image from `eclipse-temurin:11.0.16_8-jre-alpine` to `eclipse-temurin:11.0.18_10-jre-alpine`
- bump `spring-boot-starter-parent` version from `2.6.11` to `2.6.14`
- bump `httpclient` version from `4.5.10` to `4.5.14`
- manually bump `snakeyaml` to `1.33` from `1.29` that comes as a dependency from `spring-boot-starter-parent`
- manually bump `io.netty` versions from `4.1.85.Final` to `4.1.87.Final`
- kyma-incubator/compass-console#80
- kyma-incubator/compass#2868

Bump base Docker images and dependencies

---

.gitignore
components/ord-service/.gitignore
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SelfRegisteredRuntimeRepository.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/DestinationEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java

This PR adds `@EdmProtectedBy` annotations to each entity in order to allow the jpa-processor to filter based on formation. When a call to the ORD Service is made we set claims with the actual values that should be used in the `EdmProtectedBy` filtering:
- In case single tenant is present (discovery based on tenancy) - Add default formation claim `aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa` in the JPA Context.
- In case double tenant is present (consumer provider flow) -  Find all the formations that the RuntimeContext is part of and add them as formation claims in the JPA context.
**Changes proposed in this pull request**
- add `formation_id` field and annotation to the proper entities
- change repo func to return the single runtime context if present instead of the count
- add …

Filter ORD Service response based on formations for SaaS application consumers

---

components/ord-service/Dockerfile
components/ord-service/pom.xml

- bump maven base image from `3.8.7-eclipse-temurin-11-focal` to `3.9.1-eclipse-temurin-11-focal`
- bump spring boot from `2.6.14` to `2.7.10`
- bump `snakeyaml` from `1.33` to `2.0`
- kyma-incubator/compass#3022
- kyma-incubator/compass-console#83

Bump dependencies

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/config/TokenParserConfig.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SelfRegisteredRepository.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/SubscriptionHelper.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java

Allow BTP Applications onboarded as Application Templates to consume ORD Service APIs

Allow BTP Applications onboarded as Application Templates to consume ORD Service APIs

---

components/ord-service/pom.xml

Reverting the fix described in the following PR: https://github.com/SAP/olingo-jpa-processor-v4/pull/158 as the concern that Oliver brought there seems to have a bigger impact than expected. As stated in the comments that's a trade-off that we accepted at that time. However, when we did new performance evaluations it seems like the performance is better without the "fix". Back in the day we had many missing indices as well as casts and view problems that made us think otherwise.

Fix missing top-level filter in the generated SQL where clause

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/DestinationEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java

This PR adopts the changes introduced in https://github.com/kyma-incubator/compass/pull/3470. Basically, a filtering by tenant_id or formation_id is enabled instead of filtering by tenant_id or formation_id + tenant_id.
When we are in the consumer-provider flow (meaning that there are formation claims) we will be filtering by formation_id and we set for tenant claim the default tenant value.
When for formation claims there is only the default formation value, that means that we will be filtering only by tenant_id, so then we set the tenant_id in the tenant claims.
However, a new `destination_tenant_id` claims is introduced for the `DestinationEntity` which is always populated with the tenant_id. This is because we want the Destinations to be visible only for the tenant it …

Adapt tenant claims

---

components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectAPIResource.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectEventResource.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/CapabilityEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/DataProductEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/DestinationEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeMappingEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/IntegrationDependencyEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/APIBundleReference.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/APIProduct.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/BundleDestinations.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EntityTypeProduct.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EventBundleReference.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EventProduct.java
components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/PackageProduct.java

The PR is related to [this issue](https://github.com/SAP/olingo-jpa-processor-v4/issues/276). The `distinct` clause is rightly missing meaning that the assumption about it was invalid. So, another solution had to be found.
The setup in the issue is achieved by adding the Application in two formations of the same type and calling the ORD Service in the "consumer-provider flow".
The solution in this PR is that we add the `formation_id` as join column (on top of the existing ones) across all relations between the entities. This eliminates the duplicates when the given entity is in multiple formations.
- add `formation_id` as join column across all entity relations
- for the bundles <-> apis/events relation don't use the …

Remove duplicates when joining by formation_id as well
